-- EXPLORATORY DATA ANALYSIS (EDA) 

--  OPERATIONAL INSIGHTS
-- Numbers of appiontments by Doctor's Specializations
SELECT specialization, COUNT(*) AS total_appointments
FROM doctors d
JOIN appointments a 
	ON a.doctor_id = d.doctor_id
GROUP BY specialization
ORDER BY total_appointments DESC;

-- Appointment Status Breakdown by Branch
SELECT d.hospital_branch, a.`status`, COUNT(*) AS total
FROM appointments a
JOIN doctors d ON a.doctor_id = d.doctor_id
GROUP BY d.hospital_branch, a.`status`;

-- Peak Appointment Days
SELECT DAYNAME(appointment_date) AS weekday,COUNT(*) AS total_appointment
FROM appointments
GROUP BY weekday
ORDER BY total_appointment DESC;

-- DOCTORS PRODUCTIVITY
-- Revenue generated by doctor's and area of specialization  Per Branch
SELECT CONCAT(d.first_name, ' ', d.last_name) AS doctor,
       d.hospital_branch,
       d.specialization,
       SUM(b.amount) AS total_revenue
FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON t.appointment_id = a.appointment_id
JOIN billing b ON b.treatment_id = t.treatment_id
WHERE b.payment_status = 'Paid'
GROUP BY doctor, d.hospital_branch,d.specialization
ORDER BY total_revenue DESC;

--  Appointment with doctors & patient
SELECT COUNT(a.appointment_id) AS total_app,
CONCAT(d.first_name, ' ',d.last_name) AS doctor,d.hospital_branch
FROM appointments a
JOIN patients p
ON a.patient_id =p.patient_id
JOIN doctors d
	ON d.doctor_id = a.doctor_id
GROUP BY doctor,d.hospital_branch
ORDER BY total_app DESC ;



-- REVENUE & Biling Analysis
-- Total Revenue by Payment Status
SELECT payment_status,
	CAST(SUM(amount) AS DECIMAL(8,2)) AS total_amount
FROM billing 
GROUP BY payment_status;

-- High failed payment method
SELECT payment_method, COUNT(*) AS failed_count
FROM billing
WHERE payment_status = 'Failed'
GROUP BY payment_method
ORDER BY failed_count DESC;

-- INSURANCE OPTIMIZATION
-- Most used insurance provider
SELECT insurance_provider, COUNT(*) AS num_patients
FROM patients
GROUP BY insurance_provider
ORDER BY num_patients DESC;

-- Amount successfully Paid by Insurance Provider
SELECT p.insurance_provider, SUM(b.amount) AS total_cost
FROM billing b
JOIN patients p ON b.patient_id = p.patient_id
WHERE b.payment_status = 'Paid'
GROUP BY p.insurance_provider
ORDER BY total_cost DESC;

-- PATIENT SEGEMENTATION
-- Top 10 spending patients
SELECT CONCAT(p.first_name, ' ', p.last_name) AS patient,
       SUM(b.amount) AS total_paid
FROM patients p
JOIN billing b ON p.patient_id = b.patient_id
WHERE b.payment_status = 'Paid'
GROUP BY patient
ORDER BY total_paid DESC
LIMIT 10;

-- patients with the most visit
SELECT p.patient_id, CONCAT(p.first_name, ' ', p.last_name) AS patient,
       COUNT(a.appointment_id) AS total_visits
FROM patients p
JOIN appointments a ON p.patient_id = a.patient_id
GROUP BY p.patient_id, patient
HAVING total_visits > 1
ORDER BY total_visits DESC;


